version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - ../app/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./runtime/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crm-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  prettier:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../app:/app
    command: sh -c "npm install -g prettier && npx prettier --write . --parser css"
    user: "${UID}:${GID}"

  mailpit:
    container_name: lms-mailpit
    image: axllent/mailpit
    networks:
      - crm-network
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  crm-network:
    driver: bridge

