"""update image url field

Revision ID: 6c093307cbdc
Revises: 1403369b892e
Create Date: 2026-07-04 10:45:15.675554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c093307cbdc"
down_revision: Union[str, Sequence[str], None] = "1403369b892e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "image_url",
        existing_type=sa.VARCHAR(length=255),
        comment="",
        existing_nullable=False,
        nullable=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "image_url",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="",
        existing_nullable=False,
        nullable=False
    )
