"""create email token table

Revision ID: eb430226ae0a
Revises: 6190b651686f
Create Date: 2026-05-10 10:45:07.376181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eb430226ae0a"
down_revision: Union[str, Sequence[str], None] = "6190b651686f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_tokens",
        sa.Column(
            "entity_type",
            sa.SmallInteger(),
            nullable=False,
            comment="Owner type",
        ),
        sa.Column(
            "entity_id", sa.Integer(), nullable=False, comment="Owner type"
        ),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN (1, 2)", name="ck_entity_type_valid_values"
        ),
        sa.CheckConstraint("type IN (1)", name="ck_type_valid_values"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )


def downgrade() -> None:
    op.drop_table("email_tokens")
    # ### end Alembic commands ###
